<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>

		<RootNamespace>TANGERINE_ZIP</RootNamespace>

		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>

		<UserSecretsId>655049f4-4e69-449c-824a-293a9573c864</UserSecretsId>

		<!-- 默认资源语言 -->
		<NeutralLanguage>en-US</NeutralLanguage>

		<!-- 发布目标 -->
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>

		<!-- .NET 官方单文件发布 -->
		<PublishSingleFile>true</PublishSingleFile>

		<!-- 将 Native DLL 尽可能打入单文件 -->
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

		<!-- 对单文件中的程序集进行压缩 -->
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

		<!-- Reflection-based archive libraries are not compatible with trimming. -->
		<PublishTrimmed>false</PublishTrimmed>

		<!-- 不输出调试符号 -->
		<DebugType>None</DebugType>
		<DebugSymbols>false</DebugSymbols>

		<!-- 只发布需要的卫星语言资源 -->
		<SatelliteResourceLanguages>en-US;zh-CN;zh-TW;zh-HK;zh-MO</SatelliteResourceLanguages>

	</PropertyGroup>


	<!-- SmokeTests 可以访问内部成员 -->
	<ItemGroup>
		<InternalsVisibleTo Include="TANGERINE-ZIP.SmokeTests" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Resources\Kiro.png;Resources\TZIP.png" />
		<EmbeddedResource Include="Embedded\TangerineZipContextMenu.msix" LogicalName="TANGERINE_ZIP.ContextMenu.TangerineZipContextMenu.msix" />
		<EmbeddedResource Include="Embedded\TangerineZipContextMenu.cer" LogicalName="TANGERINE_ZIP.ContextMenu.TangerineZipContextMenu.cer" />
		<EmbeddedResource Include="..\third_party\ContextMenuForWindows11\LICENSE" LogicalName="TANGERINE_ZIP.ContextMenu.LGPL-3.0.txt" />
		<EmbeddedResource Include="Embedded\SevenZip\7z.exe" LogicalName="TANGERINE_ZIP.SevenZip.7z.exe" />
		<EmbeddedResource Include="Embedded\SevenZip\7z.dll" LogicalName="TANGERINE_ZIP.SevenZip.7z.dll" />
		<EmbeddedResource Include="Embedded\SevenZip\License.txt" LogicalName="TANGERINE_ZIP.SevenZip.License.txt" />
	</ItemGroup>


	<!-- NuGet -->
	<ItemGroup>

		<PackageReference Include="Devedse.DiscUtils.Iso9660" Version="1.0.107" />

		<PackageReference Include="Joveler.Compression.XZ" Version="5.0.2" />

		<PackageReference Include="K4os.Compression.LZ4.Streams" Version="1.3.8" />

		<PackageReference Include="ManagedWimLib" Version="2.6.0" />

		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />

		<PackageReference Include="SharpCompress" Version="0.50.1" />
		<PackageReference Include="SharpZipLib" Version="1.4.2" />

		<!-- Fody -->

		<!-- 将托管依赖嵌入主程序集 -->

	</ItemGroup>


	<ItemGroup>
		<Compile Update="*.xaml.cs">
			<DependentUpon>%(Filename)</DependentUpon>
		</Compile>
	</ItemGroup>
</Project>
